START TRANSACTION;

INSERT INTO master_item (
    id,
    name,
    sku,
    gas_type,
    is_serialized,
    empty_weight_kg,
    gas_weight_kg,
    min_stock_alert,
    max_days_at_customer,
    created_at,
    updated_at
) VALUES
(UUID(), 'Argon - Industrial Grade (1 m3)', 'ARGON-IND-1M3', 'ARGON', 1, 16, 1.8, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Industrial Grade (2 m3)', 'ARGON-IND-2M3', 'ARGON', 1, 26, 3.5, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Industrial Grade (6 m3)', 'ARGON-IND-6M3', 'ARGON', 1, 55, 10.5, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Industrial Grade (7 m3)', 'ARGON-IND-7M3', 'ARGON', 1, 58, 12.5, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Industrial Grade (10 m3)', 'ARGON-IND-10M3', 'ARGON', 1, 78, 17.5, 10, 0, NOW(), NOW()),
(UUID(), 'Hydrogen - Industrial Grade (1 m3)', 'HYDROGEN-IND-1M3', 'HYDROGEN', 1, 15, 0.09, 10, 0, NOW(), NOW()),
(UUID(), 'Hydrogen - Industrial Grade (2 m3)', 'HYDROGEN-IND-2M3', 'HYDROGEN', 1, 24, 0.18, 10, 0, NOW(), NOW()),
(UUID(), 'Hydrogen - Industrial Grade (6 m3)', 'HYDROGEN-IND-6M3', 'HYDROGEN', 1, 48, 0.54, 10, 0, NOW(), NOW()),
(UUID(), 'Hydrogen - Industrial Grade (7 m3)', 'HYDROGEN-IND-7M3', 'HYDROGEN', 1, 50, 0.63, 10, 0, NOW(), NOW()),
(UUID(), 'Hydrogen - Industrial Grade (10 m3)', 'HYDROGEN-IND-10M3', 'HYDROGEN', 1, 68, 0.9, 10, 0, NOW(), NOW()),
(UUID(), 'Oxygen - Industrial Grade (1 m3)', 'OXYGEN-IND-1M3', 'OXYGEN', 1, 16, 1.4, 10, 0, NOW(), NOW()),
(UUID(), 'Oxygen - Industrial Grade (2 m3)', 'OXYGEN-IND-2M3', 'OXYGEN', 1, 26, 2.9, 10, 0, NOW(), NOW()),
(UUID(), 'Oxygen - Industrial Grade (6 m3)', 'OXYGEN-IND-6M3', 'OXYGEN', 1, 52, 8.6, 10, 0, NOW(), NOW()),
(UUID(), 'Oxygen - Industrial Grade (7 m3)', 'OXYGEN-IND-7M3', 'OXYGEN', 1, 55, 10, 10, 0, NOW(), NOW()),
(UUID(), 'Oxygen - Industrial Grade (10 m3)', 'OXYGEN-IND-10M3', 'OXYGEN', 1, 75, 14.3, 10, 0, NOW(), NOW()),
(UUID(), 'Nitrogen - Industrial Grade (1 m3)', 'NITROGEN-IND-1M3', 'NITROGEN', 1, 16, 1.25, 10, 0, NOW(), NOW()),
(UUID(), 'Nitrogen - Industrial Grade (2 m3)', 'NITROGEN-IND-2M3', 'NITROGEN', 1, 26, 2.5, 10, 0, NOW(), NOW()),
(UUID(), 'Nitrogen - Industrial Grade (6 m3)', 'NITROGEN-IND-6M3', 'NITROGEN', 1, 52, 7.5, 10, 0, NOW(), NOW()),
(UUID(), 'Nitrogen - Industrial Grade (7 m3)', 'NITROGEN-IND-7M3', 'NITROGEN', 1, 55, 8.8, 10, 0, NOW(), NOW()),
(UUID(), 'Nitrogen - Industrial Grade (10 m3)', 'NITROGEN-IND-10M3', 'NITROGEN', 1, 75, 12.5, 10, 0, NOW(), NOW()),
(UUID(), 'Acetylene - Welding Grade (2 kg)', 'ACETYLENE-WELD-2KG', 'ACETYLENE', 1, 22, 2, 10, 0, NOW(), NOW()),
(UUID(), 'Acetylene - Welding Grade (5 kg)', 'ACETYLENE-WELD-5KG', 'ACETYLENE', 1, 32, 5, 10, 0, NOW(), NOW()),
(UUID(), 'Acetylene - Welding Grade (7 kg)', 'ACETYLENE-WELD-7KG', 'ACETYLENE', 1, 38, 7, 10, 0, NOW(), NOW()),
(UUID(), 'Carbondioxide - Industrial Grade (5 kg)', 'CO2-IND-5KG', 'CARBON_DIOXIDE', 1, 18, 5, 10, 0, NOW(), NOW()),
(UUID(), 'Carbondioxide - Industrial Grade (25 kg)', 'CO2-IND-25KG', 'CARBON_DIOXIDE', 1, 45, 25, 10, 0, NOW(), NOW()),
(UUID(), 'Carbondioxide - Industrial Grade (32 kg)', 'CO2-IND-32KG', 'CARBON_DIOXIDE', 1, 52, 32, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Dioxide - Ultra High Purity (5 kg)', 'CO2-UHP-5KG', 'CARBON_DIOXIDE', 1, 18, 5, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Dioxide - Ultra High Purity (25 kg)', 'CO2-UHP-25KG', 'CARBON_DIOXIDE', 1, 45, 25, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Dioxide - Ultra High Purity (32 kg)', 'CO2-UHP-32KG', 'CARBON_DIOXIDE', 1, 52, 32, 10, 0, NOW(), NOW()),
(UUID(), 'Hidrogen - Ultra High Purity (1 m3)', 'HYDROGEN-UHP-1M3', 'HYDROGEN', 1, 15, 0.09, 10, 0, NOW(), NOW()),
(UUID(), 'Hidrogen - Ultra High Purity (2 m3)', 'HYDROGEN-UHP-2M3', 'HYDROGEN', 1, 24, 0.18, 10, 0, NOW(), NOW()),
(UUID(), 'Hidrogen - Ultra High Purity (6 m3)', 'HYDROGEN-UHP-6M3', 'HYDROGEN', 1, 48, 0.54, 10, 0, NOW(), NOW()),
(UUID(), 'Hidrogen - Ultra High Purity (7 m3)', 'HYDROGEN-UHP-7M3', 'HYDROGEN', 1, 50, 0.63, 10, 0, NOW(), NOW()),
(UUID(), 'Hidrogen - Ultra High Purity (10 m3)', 'HYDROGEN-UHP-10M3', 'HYDROGEN', 1, 68, 0.9, 10, 0, NOW(), NOW()),
(UUID(), 'Helium - Ultra High Purity (1 m3)', 'HELIUM-UHP-1M3', 'HELIUM', 1, 16, 0.18, 10, 0, NOW(), NOW()),
(UUID(), 'Helium - Ultra High Purity (2 m3)', 'HELIUM-UHP-2M3', 'HELIUM', 1, 26, 0.36, 10, 0, NOW(), NOW()),
(UUID(), 'Helium - Ultra High Purity (6 m3)', 'HELIUM-UHP-6M3', 'HELIUM', 1, 55, 1.1, 10, 0, NOW(), NOW()),
(UUID(), 'Helium - Ultra High Purity (7 m3)', 'HELIUM-UHP-7M3', 'HELIUM', 1, 58, 1.25, 10, 0, NOW(), NOW()),
(UUID(), 'Helium - Ultra High Purity (10 m3)', 'HELIUM-UHP-10M3', 'HELIUM', 1, 78, 1.8, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Monoxide (CO) - Laboratories Grade (1 m3)', 'CO-LAB-1M3', 'CARBON_MONOXIDE', 1, 16, 1.25, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Monoxide (CO) - Laboratories Grade (2 m3)', 'CO-LAB-2M3', 'CARBON_MONOXIDE', 1, 26, 2.5, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Monoxide (CO) - Laboratories Grade (6 m3)', 'CO-LAB-6M3', 'CARBON_MONOXIDE', 1, 52, 7.5, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Monoxide (CO) - Laboratories Grade (7 m3)', 'CO-LAB-7M3', 'CARBON_MONOXIDE', 1, 55, 8.8, 10, 0, NOW(), NOW()),
(UUID(), 'Carbon Monoxide (CO) - Laboratories Grade (10 m3)', 'CO-LAB-10M3', 'CARBON_MONOXIDE', 1, 75, 12.5, 10, 0, NOW(), NOW()),
(UUID(), 'Ethylene Oxide EtO - Medical Grade (10 kg)', 'ETO-MED-10KG', 'ETHYLENE_OXIDE', 1, 28, 10, 10, 0, NOW(), NOW()),
(UUID(), 'Ethylene Oxide EtO - Medical Grade (25 kg)', 'ETO-MED-25KG', 'ETHYLENE_OXIDE', 1, 45, 25, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Ultra High Purity (1 m3)', 'ARGON-UHP-1M3', 'ARGON', 1, 16, 1.8, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Ultra High Purity (2 m3)', 'ARGON-UHP-2M3', 'ARGON', 1, 26, 3.5, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Ultra High Purity (6 m3)', 'ARGON-UHP-6M3', 'ARGON', 1, 55, 10.5, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Ultra High Purity (7 m3)', 'ARGON-UHP-7M3', 'ARGON', 1, 58, 12.5, 10, 0, NOW(), NOW()),
(UUID(), 'Argon - Ultra High Purity (10 m3)', 'ARGON-UHP-10M3', 'ARGON', 1, 78, 17.5, 10, 0, NOW(), NOW()),
(UUID(), 'Acetylene - Ultra High Purity (2 kg)', 'ACETYLENE-UHP-2KG', 'ACETYLENE', 1, 22, 2, 10, 0, NOW(), NOW()),
(UUID(), 'Acetylene - Ultra High Purity (5 kg)', 'ACETYLENE-UHP-5KG', 'ACETYLENE', 1, 32, 5, 10, 0, NOW(), NOW()),
(UUID(), 'Acetylene - Ultra High Purity (7 kg)', 'ACETYLENE-UHP-7KG', 'ACETYLENE', 1, 38, 7, 10, 0, NOW(), NOW()),
(UUID(), 'Sulfur Hexafluoride (SF6) - Ultra High Purity (10 kg)', 'SF6-UHP-10KG', 'SF6', 1, 45, 10, 10, 0, NOW(), NOW()),
(UUID(), 'Sulfur Hexafluoride (SF6) - Ultra High Purity (40 kg)', 'SF6-UHP-40KG', 'SF6', 1, 75, 40, 10, 0, NOW(), NOW()),
(UUID(), 'Ammonia 99 Percent (6 kg)', 'AMMONIA-99-6KG', 'AMMONIA', 1, 22, 6, 10, 0, NOW(), NOW()),
(UUID(), 'Ammonia 99 Percent (10 kg)', 'AMMONIA-99-10KG', 'AMMONIA', 1, 28, 10, 10, 0, NOW(), NOW()),
(UUID(), 'Ammonia 99 Percent (25 kg)', 'AMMONIA-99-25KG', 'AMMONIA', 1, 50, 25, 10, 0, NOW(), NOW()),
(UUID(), 'Morris Regulator', 'MORRIS-REGULATOR', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Cigweld Regulator', 'CIGWELD-REGULATOR', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Victor Regulator', 'VICTOR-REGULATOR', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Harris Regulator', 'HARRIS-REGULATOR', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Liquid Nitrogen Container', 'LIQUID-NITROGEN-CONTAINER', 'NITROGEN', 0, 0, 0, 2, 0, NOW(), NOW()),
(UUID(), 'Vessel Gas Liquid (VGL)', 'VESSEL-GAS-LIQUID-VGL', NULL, 0, 0, 0, 2, 0, NOW(), NOW()),
(UUID(), 'Storage Tank', 'STORAGE-TANK', NULL, 0, 0, 0, 2, 0, NOW(), NOW()),
(UUID(), 'Fire Extinguisher', 'FIRE-EXTINGUISHER', NULL, 0, 0, 0, 10, 0, NOW(), NOW()),
(UUID(), 'Medical Gas Digital Alarm', 'MEDICAL-GAS-DIGITAL-ALARM', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Zone Valve Box', 'ZONE-VALVE-BOX', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Bedhead Aluminium Panel', 'BEDHEAD-ALUMINIUM-PANEL', NULL, 0, 0, 0, 5, 0, NOW(), NOW()),
(UUID(), 'Aluminum Hospital Handrail', 'ALUMINUM-HOSPITAL-HANDRAIL', NULL, 0, 0, 0, 10, 0, NOW(), NOW()),
(UUID(), 'Hospital Vinyl Floor', 'HOSPITAL-VINYL-FLOOR', NULL, 0, 0, 0, 50, 0, NOW(), NOW());

INSERT INTO sparepart_stock (
    id,
    item_id,
    quantity,
    created_at,
    updated_at
)
SELECT
    UUID(),
    id,
    0,
    NOW(),
    NOW()
FROM master_item
WHERE sku IN (
    'MORRIS-REGULATOR',
    'CIGWELD-REGULATOR',
    'VICTOR-REGULATOR',
    'HARRIS-REGULATOR',
    'LIQUID-NITROGEN-CONTAINER',
    'VESSEL-GAS-LIQUID-VGL',
    'STORAGE-TANK',
    'FIRE-EXTINGUISHER',
    'MEDICAL-GAS-DIGITAL-ALARM',
    'ZONE-VALVE-BOX',
    'BEDHEAD-ALUMINIUM-PANEL',
    'ALUMINUM-HOSPITAL-HANDRAIL',
    'HOSPITAL-VINYL-FLOOR'
);

COMMIT;

SELECT COUNT(*) AS imported_master_items
FROM master_item
WHERE sku IN (
    'ARGON-IND-1M3', 'ARGON-IND-2M3', 'ARGON-IND-6M3', 'ARGON-IND-7M3', 'ARGON-IND-10M3',
    'HYDROGEN-IND-1M3', 'HYDROGEN-IND-2M3', 'HYDROGEN-IND-6M3', 'HYDROGEN-IND-7M3', 'HYDROGEN-IND-10M3',
    'OXYGEN-IND-1M3', 'OXYGEN-IND-2M3', 'OXYGEN-IND-6M3', 'OXYGEN-IND-7M3', 'OXYGEN-IND-10M3',
    'NITROGEN-IND-1M3', 'NITROGEN-IND-2M3', 'NITROGEN-IND-6M3', 'NITROGEN-IND-7M3', 'NITROGEN-IND-10M3',
    'ACETYLENE-WELD-2KG', 'ACETYLENE-WELD-5KG', 'ACETYLENE-WELD-7KG',
    'CO2-IND-5KG', 'CO2-IND-25KG', 'CO2-IND-32KG', 'CO2-UHP-5KG', 'CO2-UHP-25KG', 'CO2-UHP-32KG',
    'HYDROGEN-UHP-1M3', 'HYDROGEN-UHP-2M3', 'HYDROGEN-UHP-6M3', 'HYDROGEN-UHP-7M3', 'HYDROGEN-UHP-10M3',
    'HELIUM-UHP-1M3', 'HELIUM-UHP-2M3', 'HELIUM-UHP-6M3', 'HELIUM-UHP-7M3', 'HELIUM-UHP-10M3',
    'CO-LAB-1M3', 'CO-LAB-2M3', 'CO-LAB-6M3', 'CO-LAB-7M3', 'CO-LAB-10M3',
    'ETO-MED-10KG', 'ETO-MED-25KG', 'ARGON-UHP-1M3', 'ARGON-UHP-2M3', 'ARGON-UHP-6M3', 'ARGON-UHP-7M3', 'ARGON-UHP-10M3',
    'ACETYLENE-UHP-2KG', 'ACETYLENE-UHP-5KG', 'ACETYLENE-UHP-7KG', 'SF6-UHP-10KG', 'SF6-UHP-40KG',
    'AMMONIA-99-6KG', 'AMMONIA-99-10KG', 'AMMONIA-99-25KG', 'MORRIS-REGULATOR', 'CIGWELD-REGULATOR',
    'VICTOR-REGULATOR', 'HARRIS-REGULATOR', 'LIQUID-NITROGEN-CONTAINER', 'VESSEL-GAS-LIQUID-VGL', 'STORAGE-TANK',
    'FIRE-EXTINGUISHER', 'MEDICAL-GAS-DIGITAL-ALARM', 'ZONE-VALVE-BOX', 'BEDHEAD-ALUMINIUM-PANEL',
    'ALUMINUM-HOSPITAL-HANDRAIL', 'HOSPITAL-VINYL-FLOOR'
) AND deleted_at IS NULL;
